-- ------------------------- info -------------------------
-- @@ver: 1_000_029
-- @@info: 增加日志归档元数据表
-- ------------------------- info -------------------------

CREATE TABLE IF NOT EXISTS "base_log_archive" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "log_type" varchar(32) NOT NULL,
  "source_table" varchar(128) NOT NULL,
  "archive_table" varchar(128) NOT NULL,
  "archive_month" varchar(7) NOT NULL,
  "data_start_time" timestamp NULL,
  "data_end_time" timestamp NULL,
  "row_count" bigint NOT NULL DEFAULT 0,
  "status" varchar(16) NOT NULL,
  "archive_time" timestamp NULL,
  "error_message" text NULL,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) DEFAULT NULL,
  "upd_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32) DEFAULT NULL,
  "upd_name" varchar(255) DEFAULT NULL,
  "upd_host" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "base_log_archive__uk_type_month" ON "base_log_archive" ("log_type", "archive_month");
CREATE INDEX IF NOT EXISTS "base_log_archive__idx_status_month" ON "base_log_archive" ("status", "archive_month");
COMMENT ON TABLE "base_log_archive" IS '日志归档元数据';
COMMENT ON COLUMN "base_log_archive"."log_type" IS '日志类型';
COMMENT ON COLUMN "base_log_archive"."source_table" IS '原始表名';
COMMENT ON COLUMN "base_log_archive"."archive_table" IS '归档表名';
COMMENT ON COLUMN "base_log_archive"."archive_month" IS '归档月份，yyyy-MM';
COMMENT ON COLUMN "base_log_archive"."data_start_time" IS '数据开始时间';
COMMENT ON COLUMN "base_log_archive"."data_end_time" IS '数据结束时间';
COMMENT ON COLUMN "base_log_archive"."row_count" IS '数据量';
COMMENT ON COLUMN "base_log_archive"."status" IS '归档状态';
COMMENT ON COLUMN "base_log_archive"."archive_time" IS '归档时间';
COMMENT ON COLUMN "base_log_archive"."error_message" IS '异常信息';
COMMENT ON COLUMN "base_log_archive"."crt_time" IS '创建时间';
COMMENT ON COLUMN "base_log_archive"."crt_user" IS '创建用户ID';
COMMENT ON COLUMN "base_log_archive"."crt_name" IS '创建用户';
COMMENT ON COLUMN "base_log_archive"."crt_host" IS '创建IP';
COMMENT ON COLUMN "base_log_archive"."upd_time" IS '更新时间';
COMMENT ON COLUMN "base_log_archive"."upd_user" IS '更新用户ID';
COMMENT ON COLUMN "base_log_archive"."upd_name" IS '更新用户';
COMMENT ON COLUMN "base_log_archive"."upd_host" IS '更新IP';
DROP TRIGGER IF EXISTS "base_log_archive__upd_time" ON "base_log_archive";
CREATE TRIGGER "base_log_archive__upd_time" BEFORE UPDATE ON "base_log_archive" FOR EACH ROW EXECUTE FUNCTION fa_base_set_upd_time();
