-- ------------------------- info -------------------------
-- @@ver: 1_000_022
-- @@info: 字典base_dict表增加字段：type数值类型：1-关联列表，2-关联树，3-字符串，4-选择列表；value字典值。增加表base_dict_data。
-- ------------------------- info -------------------------
ALTER TABLE "base_dict" ADD COLUMN "type" smallint NULL;
COMMENT ON COLUMN "base_dict"."type" IS '数值类型：1-关联列表，2-关联树，3-字符串，4-选择列表';
UPDATE base_dict SET type = 4 WHERE type IS NULL;

ALTER TABLE "base_dict" ADD COLUMN "value" varchar(255) NULL;
COMMENT ON COLUMN "base_dict"."value" IS '字典值';

CREATE TABLE IF NOT EXISTS "base_dict_data" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "parent_id" integer DEFAULT NULL,
  "dict_id" integer NOT NULL,
  "sort_id" integer DEFAULT '0',
  "label" varchar(255) DEFAULT NULL,
  "value" varchar(255) DEFAULT NULL,
  "is_default" boolean DEFAULT NULL,
  "valid" boolean DEFAULT NULL,
  "description" varchar(255) DEFAULT NULL,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) DEFAULT NULL,
  "upd_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32) DEFAULT NULL,
  "upd_name" varchar(255) DEFAULT NULL,
  "upd_host" varchar(255) DEFAULT NULL,
  "deleted" boolean NOT NULL DEFAULT false,
  PRIMARY KEY ("id")
);
COMMENT ON TABLE "base_dict_data" IS 'BASE-字典值';
COMMENT ON COLUMN "base_dict_data"."id" IS 'ID';
COMMENT ON COLUMN "base_dict_data"."parent_id" IS '上级节点';
COMMENT ON COLUMN "base_dict_data"."dict_id" IS '字典分类ID';
COMMENT ON COLUMN "base_dict_data"."sort_id" IS '排序ID';
COMMENT ON COLUMN "base_dict_data"."label" IS '字典键';
COMMENT ON COLUMN "base_dict_data"."value" IS '字典值';
COMMENT ON COLUMN "base_dict_data"."is_default" IS '是否默认值：0否 1是';
COMMENT ON COLUMN "base_dict_data"."valid" IS '是否生效：0否 1是';
COMMENT ON COLUMN "base_dict_data"."description" IS '描述';
COMMENT ON COLUMN "base_dict_data"."crt_time" IS '创建时间';
COMMENT ON COLUMN "base_dict_data"."crt_user" IS '创建用户ID';
COMMENT ON COLUMN "base_dict_data"."crt_name" IS '创建用户';
COMMENT ON COLUMN "base_dict_data"."crt_host" IS '创建IP';
COMMENT ON COLUMN "base_dict_data"."upd_time" IS '更新时间';
COMMENT ON COLUMN "base_dict_data"."upd_user" IS '更新用户ID';
COMMENT ON COLUMN "base_dict_data"."upd_name" IS '更新用户';
COMMENT ON COLUMN "base_dict_data"."upd_host" IS '更新IP';
COMMENT ON COLUMN "base_dict_data"."deleted" IS '是否删除';
DROP TRIGGER IF EXISTS "base_dict_data__upd_time" ON "base_dict_data";
CREATE TRIGGER "base_dict_data__upd_time" BEFORE UPDATE ON "base_dict_data" FOR EACH ROW EXECUTE FUNCTION fa_base_set_upd_time();

-- 增加字典值演示数据
BEGIN;
INSERT INTO "base_dict" ("id", "code", "name", "parent_id", "sort_id", "description", "type", "options", "value", "crt_time", "crt_user", "crt_name", "crt_host", "upd_time", "upd_user", "upd_name", "upd_host", "deleted") VALUES (56, 'base_dict_test', '测试字典分组', 0, 3, NULL, 4, '[]', NULL, '2025-07-09 15:40:52', '1', '超级管理员', '127.0.0.1', '2025-07-18 11:41:37', NULL, NULL, NULL, false);
INSERT INTO "base_dict" ("id", "code", "name", "parent_id", "sort_id", "description", "type", "options", "value", "crt_time", "crt_user", "crt_name", "crt_host", "upd_time", "upd_user", "upd_name", "upd_host", "deleted") VALUES (57, 'base_dict_test_options', '测试字典-选择列表', 56, 0, NULL, 4, '[{"id": 1, "label": "选项1", "value": "1", "deleted": false}, {"id": 2, "label": "选项2", "value": "2", "deleted": false}]', NULL, '2025-07-09 15:41:47', '1', '超级管理员', '127.0.0.1', '2025-07-18 11:41:37', '1', '超级管理员', '127.0.0.1', false);
INSERT INTO "base_dict" ("id", "code", "name", "parent_id", "sort_id", "description", "type", "options", "value", "crt_time", "crt_user", "crt_name", "crt_host", "upd_time", "upd_user", "upd_name", "upd_host", "deleted") VALUES (58, 'base_dict_test_text', '测试字典-字符串', 56, 1, NULL, 3, '[]', '12', '2025-07-09 15:44:16', '1', '超级管理员', '127.0.0.1', '2025-07-18 11:41:37', '1', '超级管理员', '127.0.0.1', false);
INSERT INTO "base_dict" ("id", "code", "name", "parent_id", "sort_id", "description", "type", "options", "value", "crt_time", "crt_user", "crt_name", "crt_host", "upd_time", "upd_user", "upd_name", "upd_host", "deleted") VALUES (59, 'base_dict_test_link_options', '测试字典-关联列表', 56, 2, NULL, 1, '[]', NULL, '2025-07-10 10:47:00', '1', '超级管理员', '127.0.0.1', '2025-07-18 11:41:37', '1', '超级管理员', '127.0.0.1', false);
INSERT INTO "base_dict" ("id", "code", "name", "parent_id", "sort_id", "description", "type", "options", "value", "crt_time", "crt_user", "crt_name", "crt_host", "upd_time", "upd_user", "upd_name", "upd_host", "deleted") VALUES (60, 'base_dict_test_link_tree', '测试字典-关联树', 56, 3, NULL, 2, '[]', NULL, '2025-07-10 10:47:20', '1', '超级管理员', '127.0.0.1', '2025-07-18 11:41:37', '1', '超级管理员', '127.0.0.1', false);
COMMIT;

BEGIN;
INSERT INTO "base_dict_data" ("id", "parent_id", "dict_id", "sort_id", "label", "value", "is_default", "valid", "description", "crt_time", "crt_user", "crt_name", "crt_host", "upd_time", "upd_user", "upd_name", "upd_host", "deleted") VALUES (1, 0, 59, 0, '选项1', '1', false, true, '12', '2025-07-10 16:46:44', '1', '超级管理员', '127.0.0.1', '2025-07-18 15:31:10', '1', '超级管理员', '127.0.0.1', false);
INSERT INTO "base_dict_data" ("id", "parent_id", "dict_id", "sort_id", "label", "value", "is_default", "valid", "description", "crt_time", "crt_user", "crt_name", "crt_host", "upd_time", "upd_user", "upd_name", "upd_host", "deleted") VALUES (2, 0, 59, 1, '选项2', '2', false, true, NULL, '2025-07-10 16:46:54', '1', '超级管理员', '127.0.0.1', '2025-07-18 15:32:19', '1', '超级管理员', '127.0.0.1', false);
INSERT INTO "base_dict_data" ("id", "parent_id", "dict_id", "sort_id", "label", "value", "is_default", "valid", "description", "crt_time", "crt_user", "crt_name", "crt_host", "upd_time", "upd_user", "upd_name", "upd_host", "deleted") VALUES (3, 0, 60, 2, '选项1', '1', true, true, NULL, '2025-07-10 16:54:34', '1', '超级管理员', '127.0.0.1', '2025-07-18 15:24:32', '1', '超级管理员', '127.0.0.1', false);
INSERT INTO "base_dict_data" ("id", "parent_id", "dict_id", "sort_id", "label", "value", "is_default", "valid", "description", "crt_time", "crt_user", "crt_name", "crt_host", "upd_time", "upd_user", "upd_name", "upd_host", "deleted") VALUES (4, 0, 59, 3, '3', '3', true, true, '3', '2025-07-11 16:24:18', '1', '超级管理员', '127.0.0.1', '2025-07-18 15:24:32', '1', '超级管理员', '127.0.0.1', true);
INSERT INTO "base_dict_data" ("id", "parent_id", "dict_id", "sort_id", "label", "value", "is_default", "valid", "description", "crt_time", "crt_user", "crt_name", "crt_host", "upd_time", "upd_user", "upd_name", "upd_host", "deleted") VALUES (5, 0, 59, 3, '选项3', '3', NULL, true, '3', '2025-07-11 16:32:05', '1', '超级管理员', '127.0.0.1', '2025-07-18 15:24:32', '1', '超级管理员', '127.0.0.1', true);
INSERT INTO "base_dict_data" ("id", "parent_id", "dict_id", "sort_id", "label", "value", "is_default", "valid", "description", "crt_time", "crt_user", "crt_name", "crt_host", "upd_time", "upd_user", "upd_name", "upd_host", "deleted") VALUES (6, 0, 59, 2, '选项3', '3', false, true, '3', '2025-07-11 16:33:23', '1', '超级管理员', '127.0.0.1', '2025-07-18 15:32:47', '1', '超级管理员', '127.0.0.1', false);
INSERT INTO "base_dict_data" ("id", "parent_id", "dict_id", "sort_id", "label", "value", "is_default", "valid", "description", "crt_time", "crt_user", "crt_name", "crt_host", "upd_time", "upd_user", "upd_name", "upd_host", "deleted") VALUES (7, 3, 60, 0, '选项1-1', '1-1', false, true, NULL, '2025-07-11 17:30:03', '1', '超级管理员', '127.0.0.1', '2025-07-18 15:24:32', '1', '超级管理员', '127.0.0.1', false);
INSERT INTO "base_dict_data" ("id", "parent_id", "dict_id", "sort_id", "label", "value", "is_default", "valid", "description", "crt_time", "crt_user", "crt_name", "crt_host", "upd_time", "upd_user", "upd_name", "upd_host", "deleted") VALUES (8, 0, 60, 3, '选项2', '2', false, true, NULL, '2025-07-17 17:04:21', '1', '超级管理员', '127.0.0.1', '2025-07-18 15:33:11', '1', '超级管理员', '127.0.0.1', false);
COMMIT;

SELECT setval(pg_get_serial_sequence('base_dict', 'id'), COALESCE((SELECT MAX("id") FROM "base_dict"), 1), true);
SELECT setval(pg_get_serial_sequence('base_dict_data', 'id'), COALESCE((SELECT MAX("id") FROM "base_dict_data"), 1), true);
