-- ------------------------- info -------------------------
-- @@ver: 1_000_036
-- @@info: 统一 Telemetry 租户ID字段类型，增加租户权限范围和查询索引
-- ------------------------- info -------------------------

ALTER TABLE "base_client_error_event"
    ALTER COLUMN "tenant_id" TYPE varchar(32)
    USING "tenant_id"::varchar(32);

ALTER TABLE "base_stat_event"
    ALTER COLUMN "tenant_id" TYPE varchar(32)
    USING "tenant_id"::varchar(32);

CREATE TABLE IF NOT EXISTS "tn_tenant_permission" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "tenant_id" varchar(32) NOT NULL,
  "menu_id" integer NOT NULL,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) DEFAULT NULL,
  "upd_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32) DEFAULT NULL,
  "upd_name" varchar(255) DEFAULT NULL,
  "upd_host" varchar(255) DEFAULT NULL,
  "deleted" boolean NOT NULL DEFAULT false,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "tn_tenant_permission__uk_tenant_menu"
    ON "tn_tenant_permission" ("tenant_id", "menu_id");
CREATE INDEX IF NOT EXISTS "tn_tenant_permission__idx_menu_id"
    ON "tn_tenant_permission" ("menu_id");
COMMENT ON TABLE "tn_tenant_permission" IS '租户权限范围';
COMMENT ON COLUMN "tn_tenant_permission"."id" IS 'ID';
COMMENT ON COLUMN "tn_tenant_permission"."tenant_id" IS '租户ID';
COMMENT ON COLUMN "tn_tenant_permission"."menu_id" IS '权限ID';
COMMENT ON COLUMN "tn_tenant_permission"."crt_time" IS '创建时间';
COMMENT ON COLUMN "tn_tenant_permission"."crt_user" IS '创建用户ID';
COMMENT ON COLUMN "tn_tenant_permission"."crt_name" IS '创建用户';
COMMENT ON COLUMN "tn_tenant_permission"."crt_host" IS '创建IP';
COMMENT ON COLUMN "tn_tenant_permission"."upd_time" IS '更新时间';
COMMENT ON COLUMN "tn_tenant_permission"."upd_user" IS '更新用户ID';
COMMENT ON COLUMN "tn_tenant_permission"."upd_name" IS '更新用户';
COMMENT ON COLUMN "tn_tenant_permission"."upd_host" IS '更新IP';
COMMENT ON COLUMN "tn_tenant_permission"."deleted" IS '是否删除';
DROP TRIGGER IF EXISTS "tn_tenant_permission__upd_time" ON "tn_tenant_permission";
CREATE TRIGGER "tn_tenant_permission__upd_time"
    BEFORE UPDATE ON "tn_tenant_permission"
    FOR EACH ROW EXECUTE FUNCTION fa_base_set_upd_time();

-- 租户私有/租户范围查询索引
CREATE INDEX IF NOT EXISTS "base_department__idx_tenant_id"
    ON "base_department" ("tenant_id");
CREATE INDEX IF NOT EXISTS "base_rbac_role__idx_tenant_id"
    ON "base_rbac_role" ("tenant_id");
