-- ------------------------- info -------------------------
-- @@ver: 1_000_034
-- @@info: 增加统一工作日与交易日历基础表
-- ------------------------- info -------------------------

CREATE TABLE IF NOT EXISTS "base_calendar" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "calendar_code" varchar(32) NOT NULL,
  "name" varchar(64) NOT NULL,
  "calendar_type" varchar(16) NOT NULL,
  "market" varchar(16) DEFAULT NULL,
  "timezone" varchar(64) NOT NULL,
  "enabled" boolean NOT NULL DEFAULT true,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) DEFAULT NULL,
  "upd_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32) DEFAULT NULL,
  "upd_name" varchar(255) DEFAULT NULL,
  "upd_host" varchar(255) DEFAULT NULL,
  "deleted" boolean NOT NULL DEFAULT false,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "base_calendar__uk_code" ON "base_calendar" ("calendar_code");
COMMENT ON TABLE "base_calendar" IS '统一工作日与交易日历定义';
COMMENT ON COLUMN "base_calendar"."calendar_code" IS '日历编码';
COMMENT ON COLUMN "base_calendar"."calendar_type" IS '日历类型：OA/交易';
COMMENT ON COLUMN "base_calendar"."market" IS '对应市场';
COMMENT ON COLUMN "base_calendar"."timezone" IS '日期解释时区';
COMMENT ON COLUMN "base_calendar"."enabled" IS '是否启用';

CREATE TABLE IF NOT EXISTS "base_calendar_day" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "calendar_code" varchar(32) NOT NULL,
  "calendar_date" date NOT NULL,
  "day_type" varchar(24) NOT NULL,
  "is_open" boolean NOT NULL,
  "holiday_name" varchar(128) DEFAULT NULL,
  "source" varchar(64) DEFAULT NULL,
  "source_version" varchar(64) DEFAULT NULL,
  "remark" varchar(512) DEFAULT NULL,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) DEFAULT NULL,
  "upd_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32) DEFAULT NULL,
  "upd_name" varchar(255) DEFAULT NULL,
  "upd_host" varchar(255) DEFAULT NULL,
  "deleted" boolean NOT NULL DEFAULT false,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "base_calendar_day__uk_code_date"
  ON "base_calendar_day" ("calendar_code", "calendar_date");
CREATE INDEX IF NOT EXISTS "base_calendar_day__idx_lookup"
  ON "base_calendar_day" ("calendar_code", "calendar_date", "is_open");
COMMENT ON TABLE "base_calendar_day" IS '统一日历单日事实';
COMMENT ON COLUMN "base_calendar_day"."calendar_code" IS '日历编码';
COMMENT ON COLUMN "base_calendar_day"."calendar_date" IS '日历日期';
COMMENT ON COLUMN "base_calendar_day"."day_type" IS '日期类型';
COMMENT ON COLUMN "base_calendar_day"."is_open" IS '对所属日历是否开放';
COMMENT ON COLUMN "base_calendar_day"."holiday_name" IS '节假日或特殊日期名称';
COMMENT ON COLUMN "base_calendar_day"."source" IS '数据来源';
COMMENT ON COLUMN "base_calendar_day"."source_version" IS '来源版本或导入批次';

INSERT INTO "base_calendar"
    ("calendar_code", "name", "calendar_type", "market", "timezone", "enabled",
     "crt_time", "crt_user", "crt_name", "crt_host", "deleted")
SELECT 'CN_OA', '中国 OA 工作日历', 'OA', NULL, 'Asia/Shanghai', TRUE,
       CURRENT_TIMESTAMP, '1', '系统初始化', '127.0.0.1', FALSE
WHERE NOT EXISTS (SELECT 1 FROM "base_calendar" WHERE "calendar_code" = 'CN_OA');

INSERT INTO "base_calendar"
    ("calendar_code", "name", "calendar_type", "market", "timezone", "enabled",
     "crt_time", "crt_user", "crt_name", "crt_host", "deleted")
SELECT 'CN_A_SHARE', '沪深 A 股交易日历', 'TRADING', 'SHSZ', 'Asia/Shanghai', TRUE,
       CURRENT_TIMESTAMP, '1', '系统初始化', '127.0.0.1', FALSE
WHERE NOT EXISTS (SELECT 1 FROM "base_calendar" WHERE "calendar_code" = 'CN_A_SHARE');

INSERT INTO "base_calendar"
    ("calendar_code", "name", "calendar_type", "market", "timezone", "enabled",
     "crt_time", "crt_user", "crt_name", "crt_host", "deleted")
SELECT 'HK_STOCK', '港股交易日历', 'TRADING', 'HK', 'Asia/Hong_Kong', TRUE,
       CURRENT_TIMESTAMP, '1', '系统初始化', '127.0.0.1', FALSE
WHERE NOT EXISTS (SELECT 1 FROM "base_calendar" WHERE "calendar_code" = 'HK_STOCK');

INSERT INTO "base_calendar"
    ("calendar_code", "name", "calendar_type", "market", "timezone", "enabled",
     "crt_time", "crt_user", "crt_name", "crt_host", "deleted")
SELECT 'US_STOCK', '美股交易日历（预留）', 'TRADING', 'US', 'America/New_York', FALSE,
       CURRENT_TIMESTAMP, '1', '系统初始化', '127.0.0.1', FALSE
WHERE NOT EXISTS (SELECT 1 FROM "base_calendar" WHERE "calendar_code" = 'US_STOCK');
