-- ------------------------- info -------------------------
-- @@ver: 1_000_033
-- @@info: 增加客户端异常 Issue 与事件表
-- ------------------------- info -------------------------

CREATE TABLE IF NOT EXISTS "base_client_error_issue" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "app_id" bigint NOT NULL,
  "client_type" varchar(16) NOT NULL,
  "fingerprint" varchar(64) NOT NULL,
  "title" varchar(500) NOT NULL,
  "error_type" varchar(128) NOT NULL,
  "status" varchar(16) NOT NULL DEFAULT 'OPEN',
  "first_seen_time" timestamp NOT NULL,
  "last_seen_time" timestamp NOT NULL,
  "event_count" bigint NOT NULL DEFAULT 0,
  "user_count" bigint NOT NULL DEFAULT 0,
  "latest_release" varchar(128) DEFAULT NULL,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "client_error_issue__uk_fingerprint" ON "base_client_error_issue" ("app_id", "client_type", "fingerprint");
CREATE INDEX IF NOT EXISTS "client_error_issue__idx_filter" ON "base_client_error_issue" ("app_id", "client_type", "status", "last_seen_time");
COMMENT ON TABLE "base_client_error_issue" IS '客户端异常聚合Issue';

CREATE TABLE IF NOT EXISTS "base_client_error_event" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "app_id" bigint NOT NULL,
  "issue_id" bigint NOT NULL,
  "client_type" varchar(16) NOT NULL,
  "environment" varchar(16) NOT NULL,
  "release" varchar(128) NOT NULL,
  "session_id" varchar(64) NOT NULL,
  "user_id" varchar(64) DEFAULT NULL,
  "tenant_id" varchar(64) DEFAULT NULL,
  "error_type" varchar(128) NOT NULL,
  "message" varchar(2000) NOT NULL,
  "stack" text DEFAULT NULL,
  "breadcrumbs" jsonb DEFAULT NULL,
  "context" jsonb DEFAULT NULL,
  "occur_time" timestamp NOT NULL,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "client_error_event__idx_issue_time" ON "base_client_error_event" ("issue_id", "occur_time");
CREATE INDEX IF NOT EXISTS "client_error_event__idx_filter" ON "base_client_error_event" ("app_id", "client_type", "environment", "occur_time");
CREATE INDEX IF NOT EXISTS "client_error_event__idx_user" ON "base_client_error_event" ("user_id");
COMMENT ON TABLE "base_client_error_event" IS '客户端异常事件';
