-- ------------------------- info -------------------------
-- @@ver: 1_000_041
-- @@info: 增加推送设备绑定表
-- ------------------------- info -------------------------

CREATE TABLE IF NOT EXISTS "base_push_device" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" varchar(32) NOT NULL,
  "provider" varchar(32) NOT NULL,
  "client_id" varchar(255) NOT NULL,
  "app_id" varchar(128) NOT NULL,
  "platform" varchar(32) NOT NULL,
  "environment" varchar(16) NOT NULL,
  "enabled" boolean NOT NULL DEFAULT true,
  "last_seen_time" timestamp DEFAULT NULL,
  "invalid_time" timestamp DEFAULT NULL,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) DEFAULT NULL,
  "upd_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32) DEFAULT NULL,
  "upd_name" varchar(255) DEFAULT NULL,
  "upd_host" varchar(255) DEFAULT NULL,
  "deleted" boolean NOT NULL DEFAULT false,
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "base_push_device__uk_binding"
  ON "base_push_device" ("provider", "client_id", "app_id", "environment");
CREATE INDEX IF NOT EXISTS "base_push_device__idx_user_enabled"
  ON "base_push_device" ("user_id", "enabled");

COMMENT ON TABLE "base_push_device" IS 'BASE-推送设备';
COMMENT ON COLUMN "base_push_device"."id" IS 'ID';
COMMENT ON COLUMN "base_push_device"."user_id" IS '用户ID';
COMMENT ON COLUMN "base_push_device"."provider" IS '推送服务商';
COMMENT ON COLUMN "base_push_device"."client_id" IS 'Push Client ID';
COMMENT ON COLUMN "base_push_device"."app_id" IS '应用ID';
COMMENT ON COLUMN "base_push_device"."platform" IS '平台';
COMMENT ON COLUMN "base_push_device"."environment" IS '推送环境';
COMMENT ON COLUMN "base_push_device"."enabled" IS '是否启用';
COMMENT ON COLUMN "base_push_device"."last_seen_time" IS '最后上报时间';
COMMENT ON COLUMN "base_push_device"."invalid_time" IS '失效时间';
COMMENT ON COLUMN "base_push_device"."crt_time" IS '创建时间';
COMMENT ON COLUMN "base_push_device"."crt_user" IS '创建用户ID';
COMMENT ON COLUMN "base_push_device"."crt_name" IS '创建用户';
COMMENT ON COLUMN "base_push_device"."crt_host" IS '创建IP';
COMMENT ON COLUMN "base_push_device"."upd_time" IS '更新时间';
COMMENT ON COLUMN "base_push_device"."upd_user" IS '更新用户ID';
COMMENT ON COLUMN "base_push_device"."upd_name" IS '更新用户';
COMMENT ON COLUMN "base_push_device"."upd_host" IS '更新IP';
COMMENT ON COLUMN "base_push_device"."deleted" IS '逻辑删除';

DROP TRIGGER IF EXISTS "base_push_device__upd_time" ON "base_push_device";
CREATE TRIGGER "base_push_device__upd_time"
  BEFORE UPDATE ON "base_push_device"
  FOR EACH ROW EXECUTE FUNCTION fa_base_set_upd_time();
