-- ------------------------- info -------------------------
-- @@ver: 1_000_035
-- @@info: 增加 Telemetry 每日聚合统计表
-- ------------------------- info -------------------------

CREATE TABLE IF NOT EXISTS "base_stat_daily" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "stat_date" date NOT NULL,
  "app_id" bigint NOT NULL,
  "client_type" varchar(16) NOT NULL,
  "environment" varchar(16) NOT NULL,
  "event_type" varchar(32) NOT NULL,
  "event_code" varchar(128) NOT NULL,
  "module" varchar(128) DEFAULT NULL,
  "pv" bigint NOT NULL DEFAULT 0,
  "uv" bigint NOT NULL DEFAULT 0,
  "success_count" bigint NOT NULL DEFAULT 0,
  "fail_count" bigint NOT NULL DEFAULT 0,
  "avg_duration" double precision DEFAULT NULL,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "stat_daily__idx_date_filter" ON "base_stat_daily" ("stat_date", "app_id", "client_type", "environment");
CREATE INDEX IF NOT EXISTS "stat_daily__idx_code" ON "base_stat_daily" ("event_code", "stat_date");
COMMENT ON TABLE "base_stat_daily" IS 'Telemetry每日聚合统计';
