-- ------------------------- info -------------------------
-- @@ver: 1_000_013
-- @@info: 增加用户设备表
-- ------------------------- info -------------------------

CREATE TABLE IF NOT EXISTS "base_user_device" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" varchar(32) NOT NULL,
  "device_id" varchar(255) NOT NULL,
  "model" varchar(255) DEFAULT NULL,
  "manufacturer" varchar(255) DEFAULT NULL,
  "os" varchar(255) DEFAULT NULL,
  "os_version" varchar(255) DEFAULT NULL,
  "enable" boolean NOT NULL,
  "last_online_time" timestamp NULL DEFAULT NULL,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) DEFAULT NULL,
  "upd_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32) DEFAULT NULL,
  "upd_name" varchar(255) DEFAULT NULL,
  "upd_host" varchar(255) DEFAULT NULL,
  "deleted" boolean NOT NULL DEFAULT false,
  PRIMARY KEY ("id")
);
COMMENT ON TABLE "base_user_device" IS 'BASE-用户设备';
COMMENT ON COLUMN "base_user_device"."id" IS 'ID';
COMMENT ON COLUMN "base_user_device"."user_id" IS '所属用户ID';
COMMENT ON COLUMN "base_user_device"."device_id" IS '设备ID';
COMMENT ON COLUMN "base_user_device"."model" IS '设备型号';
COMMENT ON COLUMN "base_user_device"."manufacturer" IS '设备厂商';
COMMENT ON COLUMN "base_user_device"."os" IS '系统';
COMMENT ON COLUMN "base_user_device"."os_version" IS '系统版本号';
COMMENT ON COLUMN "base_user_device"."enable" IS '是否允许访问';
COMMENT ON COLUMN "base_user_device"."last_online_time" IS '最后在线时间';
COMMENT ON COLUMN "base_user_device"."crt_time" IS '创建时间';
COMMENT ON COLUMN "base_user_device"."crt_user" IS '创建用户ID';
COMMENT ON COLUMN "base_user_device"."crt_name" IS '创建用户';
COMMENT ON COLUMN "base_user_device"."crt_host" IS '创建IP';
COMMENT ON COLUMN "base_user_device"."upd_time" IS '更新时间';
COMMENT ON COLUMN "base_user_device"."upd_user" IS '更新用户ID';
COMMENT ON COLUMN "base_user_device"."upd_name" IS '更新用户';
COMMENT ON COLUMN "base_user_device"."upd_host" IS '更新IP';
COMMENT ON COLUMN "base_user_device"."deleted" IS '是否删除';
DROP TRIGGER IF EXISTS "base_user_device__upd_time" ON "base_user_device";
CREATE TRIGGER "base_user_device__upd_time" BEFORE UPDATE ON "base_user_device" FOR EACH ROW EXECUTE FUNCTION fa_base_set_upd_time();
