-- ------------------------- info -------------------------
-- @@ver: 1_000_030
-- @@info: 增加 Telemetry 应用、客户端异常、业务统计事件和每日聚合统计表
-- ------------------------- info -------------------------

CREATE TABLE IF NOT EXISTS "base_telemetry_app" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "app_key" varchar(64) NOT NULL,
  "app_code" varchar(64) NOT NULL,
  "app_name" varchar(128) NOT NULL,
  "client_type" varchar(16) NOT NULL,
  "enabled" boolean NOT NULL DEFAULT true,
  "remark" varchar(500) DEFAULT NULL,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) DEFAULT NULL,
  "upd_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32) DEFAULT NULL,
  "upd_name" varchar(255) DEFAULT NULL,
  "upd_host" varchar(255) DEFAULT NULL,
  "deleted" boolean NOT NULL DEFAULT false,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "base_telemetry_app__uk_app_key" ON "base_telemetry_app" ("app_key");
CREATE UNIQUE INDEX IF NOT EXISTS "base_telemetry_app__uk_app_code" ON "base_telemetry_app" ("app_code");
COMMENT ON TABLE "base_telemetry_app" IS 'Telemetry 应用';
COMMENT ON COLUMN "base_telemetry_app"."app_key" IS '客户端上报标识';
COMMENT ON COLUMN "base_telemetry_app"."app_code" IS '应用编码';
COMMENT ON COLUMN "base_telemetry_app"."app_name" IS '应用名称';
COMMENT ON COLUMN "base_telemetry_app"."client_type" IS '客户端类型';
COMMENT ON COLUMN "base_telemetry_app"."enabled" IS '是否允许上报';
COMMENT ON COLUMN "base_telemetry_app"."remark" IS '备注';
COMMENT ON COLUMN "base_telemetry_app"."deleted" IS '逻辑删除';

CREATE TABLE IF NOT EXISTS "base_client_error_issue" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "app_id" bigint NOT NULL,
  "client_type" varchar(16) NOT NULL,
  "fingerprint" varchar(64) NOT NULL,
  "title" varchar(500) NOT NULL,
  "error_type" varchar(128) NOT NULL,
  "status" varchar(16) NOT NULL DEFAULT 'OPEN',
  "first_seen_time" timestamp NOT NULL,
  "last_seen_time" timestamp NOT NULL,
  "event_count" bigint NOT NULL DEFAULT 0,
  "user_count" bigint NOT NULL DEFAULT 0,
  "latest_release" varchar(128) DEFAULT NULL,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "client_error_issue__uk_fingerprint" ON "base_client_error_issue" ("app_id", "client_type", "fingerprint");
CREATE INDEX IF NOT EXISTS "client_error_issue__idx_filter" ON "base_client_error_issue" ("app_id", "client_type", "status", "last_seen_time");
COMMENT ON TABLE "base_client_error_issue" IS '客户端异常聚合Issue';

CREATE TABLE IF NOT EXISTS "base_client_error_event" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "app_id" bigint NOT NULL,
  "issue_id" bigint NOT NULL,
  "client_type" varchar(16) NOT NULL,
  "environment" varchar(16) NOT NULL,
  "release" varchar(128) NOT NULL,
  "session_id" varchar(64) NOT NULL,
  "user_id" varchar(64) DEFAULT NULL,
  "tenant_id" varchar(64) DEFAULT NULL,
  "error_type" varchar(128) NOT NULL,
  "message" varchar(2000) NOT NULL,
  "stack" text DEFAULT NULL,
  "breadcrumbs" jsonb DEFAULT NULL,
  "context" jsonb DEFAULT NULL,
  "occur_time" timestamp NOT NULL,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "client_error_event__idx_issue_time" ON "base_client_error_event" ("issue_id", "occur_time");
CREATE INDEX IF NOT EXISTS "client_error_event__idx_filter" ON "base_client_error_event" ("app_id", "client_type", "environment", "occur_time");
CREATE INDEX IF NOT EXISTS "client_error_event__idx_user" ON "base_client_error_event" ("user_id");
COMMENT ON TABLE "base_client_error_event" IS '客户端异常事件';

CREATE TABLE IF NOT EXISTS "base_stat_event" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "app_id" bigint NOT NULL,
  "client_type" varchar(16) NOT NULL,
  "environment" varchar(16) NOT NULL,
  "release" varchar(128) NOT NULL,
  "session_id" varchar(64) NOT NULL,
  "user_id" varchar(64) DEFAULT NULL,
  "tenant_id" varchar(64) DEFAULT NULL,
  "event_type" varchar(32) NOT NULL,
  "event_code" varchar(128) NOT NULL,
  "module" varchar(128) DEFAULT NULL,
  "biz_type" varchar(128) DEFAULT NULL,
  "biz_id" varchar(128) DEFAULT NULL,
  "result" varchar(32) DEFAULT NULL,
  "duration" bigint DEFAULT NULL,
  "properties" jsonb DEFAULT NULL,
  "context" jsonb DEFAULT NULL,
  "occur_time" timestamp NOT NULL,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "stat_event__idx_filter" ON "base_stat_event" ("app_id", "client_type", "environment", "occur_time");
CREATE INDEX IF NOT EXISTS "stat_event__idx_code_time" ON "base_stat_event" ("event_code", "occur_time");
CREATE INDEX IF NOT EXISTS "stat_event__idx_user" ON "base_stat_event" ("user_id", "occur_time");
COMMENT ON TABLE "base_stat_event" IS 'Telemetry业务统计事件';

CREATE TABLE IF NOT EXISTS "base_stat_daily" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "stat_date" date NOT NULL,
  "app_id" bigint NOT NULL,
  "client_type" varchar(16) NOT NULL,
  "environment" varchar(16) NOT NULL,
  "event_type" varchar(32) NOT NULL,
  "event_code" varchar(128) NOT NULL,
  "module" varchar(128) DEFAULT NULL,
  "pv" bigint NOT NULL DEFAULT 0,
  "uv" bigint NOT NULL DEFAULT 0,
  "success_count" bigint NOT NULL DEFAULT 0,
  "fail_count" bigint NOT NULL DEFAULT 0,
  "avg_duration" double precision DEFAULT NULL,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "stat_daily__idx_date_filter" ON "base_stat_daily" ("stat_date", "app_id", "client_type", "environment");
CREATE INDEX IF NOT EXISTS "stat_daily__idx_code" ON "base_stat_daily" ("event_code", "stat_date");
COMMENT ON TABLE "base_stat_daily" IS 'Telemetry每日聚合统计';

-- Telemetry 应用管理菜单
INSERT INTO base_rbac_menu (
  id, parent_id, name, sort, level, icon, status, link_type, link_url,
  crt_time, crt_user, crt_name, crt_host, upd_time, upd_user, upd_name, upd_host, deleted
)
SELECT 10030000, 12000000, 'Telemetry', 5, 1, 'mdi:chart-line', TRUE, 1, '/admin/system/telemetry',
  CURRENT_TIMESTAMP, '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE
WHERE NOT EXISTS (
  SELECT 1 FROM base_rbac_menu WHERE id = 10030000 OR link_url = '/admin/system/telemetry'
)
ON CONFLICT (id) DO NOTHING;

-- Telemetry 应用管理菜单
INSERT INTO base_rbac_menu (
  id, parent_id, name, sort, level, icon, status, link_type, link_url,
  crt_time, crt_user, crt_name, crt_host, upd_time, upd_user, upd_name, upd_host, deleted
)
SELECT 10030005, 10030000, '应用管理', 4, 1, NULL, TRUE, 1, '/admin/system/telemetry/app',
  CURRENT_TIMESTAMP, '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE
WHERE NOT EXISTS (
  SELECT 1 FROM base_rbac_menu WHERE id = 10030005 OR link_url = '/admin/system/telemetry/app'
)
ON CONFLICT (id) DO NOTHING;
