-- ------------------------- info -------------------------
-- @@ver: 1_000_034
-- @@info: 增加 Telemetry 业务统计事件表
-- ------------------------- info -------------------------

CREATE TABLE IF NOT EXISTS "base_stat_event" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "app_id" bigint NOT NULL,
  "client_type" varchar(16) NOT NULL,
  "environment" varchar(16) NOT NULL,
  "release" varchar(128) NOT NULL,
  "session_id" varchar(64) NOT NULL,
  "user_id" varchar(64) DEFAULT NULL,
  "tenant_id" varchar(64) DEFAULT NULL,
  "event_type" varchar(32) NOT NULL,
  "event_code" varchar(128) NOT NULL,
  "module" varchar(128) DEFAULT NULL,
  "biz_type" varchar(128) DEFAULT NULL,
  "biz_id" varchar(128) DEFAULT NULL,
  "result" varchar(32) DEFAULT NULL,
  "duration" bigint DEFAULT NULL,
  "properties" jsonb DEFAULT NULL,
  "context" jsonb DEFAULT NULL,
  "occur_time" timestamp NOT NULL,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "stat_event__idx_filter" ON "base_stat_event" ("app_id", "client_type", "environment", "occur_time");
CREATE INDEX IF NOT EXISTS "stat_event__idx_code_time" ON "base_stat_event" ("event_code", "occur_time");
CREATE INDEX IF NOT EXISTS "stat_event__idx_user" ON "base_stat_event" ("user_id", "occur_time");
COMMENT ON TABLE "base_stat_event" IS 'Telemetry业务统计事件';
