-- ------------------------- info -------------------------
-- @@ver: 1_000_048
-- @@info: 增加浏览器 Web Push 订阅表
-- ------------------------- info -------------------------

CREATE TABLE IF NOT EXISTS "base_browser_push_subscription" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" varchar(32) NOT NULL,
  "endpoint_hash" char(64) NOT NULL,
  "endpoint" text NOT NULL,
  "p256dh" varchar(128) NOT NULL,
  "auth" varchar(64) NOT NULL,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) DEFAULT NULL,
  "upd_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32) DEFAULT NULL,
  "upd_name" varchar(255) DEFAULT NULL,
  "upd_host" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "base_browser_push_subscription__uk_endpoint_hash"
  ON "base_browser_push_subscription" ("endpoint_hash");
CREATE INDEX IF NOT EXISTS "base_browser_push_subscription__idx_user"
  ON "base_browser_push_subscription" ("user_id");

COMMENT ON TABLE "base_browser_push_subscription" IS 'BASE-浏览器推送订阅';
COMMENT ON COLUMN "base_browser_push_subscription"."id" IS 'ID';
COMMENT ON COLUMN "base_browser_push_subscription"."user_id" IS '用户ID';
COMMENT ON COLUMN "base_browser_push_subscription"."endpoint_hash" IS '推送地址SHA-256';
COMMENT ON COLUMN "base_browser_push_subscription"."endpoint" IS '浏览器推送地址';
COMMENT ON COLUMN "base_browser_push_subscription"."p256dh" IS '客户端公钥';
COMMENT ON COLUMN "base_browser_push_subscription"."auth" IS '客户端认证密钥';
