-- ------------------------- info -------------------------
-- @@ver: 1_000_032
-- @@info: 增加 Telemetry 应用表
-- ------------------------- info -------------------------

CREATE TABLE IF NOT EXISTS "base_telemetry_app" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "app_key" varchar(64) NOT NULL,
  "app_code" varchar(64) NOT NULL,
  "app_name" varchar(128) NOT NULL,
  "client_type" varchar(16) NOT NULL,
  "enabled" boolean NOT NULL DEFAULT true,
  "remark" varchar(500) DEFAULT NULL,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) DEFAULT NULL,
  "upd_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32) DEFAULT NULL,
  "upd_name" varchar(255) DEFAULT NULL,
  "upd_host" varchar(255) DEFAULT NULL,
  "deleted" boolean NOT NULL DEFAULT false,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "base_telemetry_app__uk_app_key" ON "base_telemetry_app" ("app_key");
CREATE UNIQUE INDEX IF NOT EXISTS "base_telemetry_app__uk_app_code" ON "base_telemetry_app" ("app_code");
COMMENT ON TABLE "base_telemetry_app" IS 'Telemetry 应用';
COMMENT ON COLUMN "base_telemetry_app"."app_key" IS '客户端上报标识';
COMMENT ON COLUMN "base_telemetry_app"."app_code" IS '应用编码';
COMMENT ON COLUMN "base_telemetry_app"."app_name" IS '应用名称';
COMMENT ON COLUMN "base_telemetry_app"."client_type" IS '客户端类型';
COMMENT ON COLUMN "base_telemetry_app"."enabled" IS '是否允许上报';
COMMENT ON COLUMN "base_telemetry_app"."remark" IS '备注';
COMMENT ON COLUMN "base_telemetry_app"."deleted" IS '逻辑删除';
