-- ------------------------- info -------------------------
-- @@ver: 1_000_001
-- @@info: 增加BaseFileBiz通用业务附件表
-- ------------------------- info -------------------------
CREATE TABLE IF NOT EXISTS "base_file_biz" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "main_biz_id" varchar(32) NOT NULL,
  "biz_id" varchar(32) NOT NULL,
  "type" varchar(32) NULL DEFAULT NULL,
  "file_id" varchar(32) NOT NULL,
  "file_name" varchar(255) NOT NULL,
  "ext" varchar(32) NOT NULL,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) NULL DEFAULT NULL,
  "upd_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32) NULL DEFAULT NULL,
  "upd_name" varchar(255) NULL DEFAULT NULL,
  "upd_host" varchar(255) NULL DEFAULT NULL,
  "deleted" boolean NOT NULL DEFAULT false,
  PRIMARY KEY ("id")
);
COMMENT ON TABLE "base_file_biz" IS 'BASE-通用业务附件表';
COMMENT ON COLUMN "base_file_biz"."id" IS 'ID';
COMMENT ON COLUMN "base_file_biz"."main_biz_id" IS '主业务ID';
COMMENT ON COLUMN "base_file_biz"."biz_id" IS '业务ID';
COMMENT ON COLUMN "base_file_biz"."type" IS '业务类型';
COMMENT ON COLUMN "base_file_biz"."file_id" IS '附件ID';
COMMENT ON COLUMN "base_file_biz"."file_name" IS '附件名称';
COMMENT ON COLUMN "base_file_biz"."ext" IS '文件扩展名';
COMMENT ON COLUMN "base_file_biz"."crt_time" IS '创建时间';
COMMENT ON COLUMN "base_file_biz"."crt_user" IS '创建用户ID';
COMMENT ON COLUMN "base_file_biz"."crt_name" IS '创建用户';
COMMENT ON COLUMN "base_file_biz"."crt_host" IS '创建IP';
COMMENT ON COLUMN "base_file_biz"."upd_time" IS '更新时间';
COMMENT ON COLUMN "base_file_biz"."upd_user" IS '更新用户ID';
COMMENT ON COLUMN "base_file_biz"."upd_name" IS '更新用户';
COMMENT ON COLUMN "base_file_biz"."upd_host" IS '更新IP';
COMMENT ON COLUMN "base_file_biz"."deleted" IS '是否删除';
DROP TRIGGER IF EXISTS "base_file_biz__upd_time" ON "base_file_biz";
CREATE TRIGGER "base_file_biz__upd_time" BEFORE UPDATE ON "base_file_biz" FOR EACH ROW EXECUTE FUNCTION fa_base_set_upd_time();
