-- ------------------------- info -------------------------
-- @@ver: 1_000_026
-- @@info: Portal MVP 用户准入与咨询记录
-- ------------------------- info -------------------------
ALTER TABLE "base_user" ADD COLUMN "admin_enabled" boolean NOT NULL DEFAULT false;
COMMENT ON COLUMN "base_user"."admin_enabled" IS '是否允许访问后台管理端';

-- 升级前的存量用户均视为既有后台用户，避免升级后失去 Admin 访问能力。
UPDATE "base_user" SET "admin_enabled" = true WHERE "deleted" = false;

CREATE TABLE IF NOT EXISTS "portal_contact_inquiry" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(100) NOT NULL,
  "company" varchar(200) DEFAULT NULL,
  "tel" varchar(32) NOT NULL,
  "email" varchar(255) DEFAULT NULL,
  "subject" varchar(200) NOT NULL,
  "message" text NOT NULL,
  "status" smallint NOT NULL DEFAULT '0',
  "source" varchar(32) NOT NULL DEFAULT 'PORTAL',
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) DEFAULT NULL,
  "upd_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32) DEFAULT NULL,
  "upd_name" varchar(255) DEFAULT NULL,
  "upd_host" varchar(255) DEFAULT NULL,
  "deleted" boolean NOT NULL DEFAULT false,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "portal_contact_inquiry__idx_portal_contact_inquiry_status" ON "portal_contact_inquiry" ("status", "crt_time");
CREATE INDEX IF NOT EXISTS "portal_contact_inquiry__idx_portal_contact_inquiry_tel" ON "portal_contact_inquiry" ("tel");
COMMENT ON TABLE "portal_contact_inquiry" IS 'Portal-官网咨询';
COMMENT ON COLUMN "portal_contact_inquiry"."id" IS 'ID';
COMMENT ON COLUMN "portal_contact_inquiry"."name" IS '联系人';
COMMENT ON COLUMN "portal_contact_inquiry"."company" IS '公司名称';
COMMENT ON COLUMN "portal_contact_inquiry"."tel" IS '联系电话';
COMMENT ON COLUMN "portal_contact_inquiry"."email" IS '联系邮箱';
COMMENT ON COLUMN "portal_contact_inquiry"."subject" IS '咨询主题';
COMMENT ON COLUMN "portal_contact_inquiry"."message" IS '咨询内容';
COMMENT ON COLUMN "portal_contact_inquiry"."status" IS '处理状态：0待处理/1处理中/2已完成';
COMMENT ON COLUMN "portal_contact_inquiry"."source" IS '来源';
COMMENT ON COLUMN "portal_contact_inquiry"."crt_time" IS '创建时间';
COMMENT ON COLUMN "portal_contact_inquiry"."crt_user" IS '创建用户ID';
COMMENT ON COLUMN "portal_contact_inquiry"."crt_name" IS '创建用户';
COMMENT ON COLUMN "portal_contact_inquiry"."crt_host" IS '创建IP';
COMMENT ON COLUMN "portal_contact_inquiry"."upd_time" IS '更新时间';
COMMENT ON COLUMN "portal_contact_inquiry"."upd_user" IS '更新用户ID';
COMMENT ON COLUMN "portal_contact_inquiry"."upd_name" IS '更新用户';
COMMENT ON COLUMN "portal_contact_inquiry"."upd_host" IS '更新IP';
COMMENT ON COLUMN "portal_contact_inquiry"."deleted" IS '是否删除';
DROP TRIGGER IF EXISTS "portal_contact_inquiry__upd_time" ON "portal_contact_inquiry";
CREATE TRIGGER "portal_contact_inquiry__upd_time" BEFORE UPDATE ON "portal_contact_inquiry" FOR EACH ROW EXECUTE FUNCTION fa_base_set_upd_time();
