-- ------------------------- info -------------------------
-- @@ver: 1_000_011
-- @@info: 增加系统新闻表
-- ------------------------- info -------------------------

CREATE TABLE IF NOT EXISTS "base_sys_news" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "title" varchar(50) NOT NULL,
  "content" text,
  "cover" varchar(32) DEFAULT NULL,
  "author" varchar(255) DEFAULT NULL,
  "pub_time" timestamp NULL DEFAULT NULL,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) DEFAULT NULL,
  "upd_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32) DEFAULT NULL,
  "upd_name" varchar(255) DEFAULT NULL,
  "upd_host" varchar(255) DEFAULT NULL,
  "deleted" boolean NOT NULL DEFAULT false,
  PRIMARY KEY ("id")
);
COMMENT ON TABLE "base_sys_news" IS 'BASE-系统-新闻';
COMMENT ON COLUMN "base_sys_news"."id" IS 'ID';
COMMENT ON COLUMN "base_sys_news"."title" IS '标题';
COMMENT ON COLUMN "base_sys_news"."content" IS '内容';
COMMENT ON COLUMN "base_sys_news"."cover" IS '封面';
COMMENT ON COLUMN "base_sys_news"."author" IS '作者';
COMMENT ON COLUMN "base_sys_news"."pub_time" IS '发布时间';
COMMENT ON COLUMN "base_sys_news"."crt_time" IS '创建时间';
COMMENT ON COLUMN "base_sys_news"."crt_user" IS '创建用户ID';
COMMENT ON COLUMN "base_sys_news"."crt_name" IS '创建用户';
COMMENT ON COLUMN "base_sys_news"."crt_host" IS '创建IP';
COMMENT ON COLUMN "base_sys_news"."upd_time" IS '更新时间';
COMMENT ON COLUMN "base_sys_news"."upd_user" IS '更新用户ID';
COMMENT ON COLUMN "base_sys_news"."upd_name" IS '更新用户';
COMMENT ON COLUMN "base_sys_news"."upd_host" IS '更新IP';
COMMENT ON COLUMN "base_sys_news"."deleted" IS '是否删除';
DROP TRIGGER IF EXISTS "base_sys_news__upd_time" ON "base_sys_news";
CREATE TRIGGER "base_sys_news__upd_time" BEFORE UPDATE ON "base_sys_news" FOR EACH ROW EXECUTE FUNCTION fa_base_set_upd_time();
