-- ------------------------- info -------------------------
-- @@ver: 1_000_004
-- @@info: 修复crt_time字段更新自动更新
-- ------------------------- info -------------------------

ALTER TABLE "base_config" ALTER COLUMN "crt_time" TYPE timestamp;
ALTER TABLE "base_config" ALTER COLUMN "crt_time" SET NOT NULL;
ALTER TABLE "base_config" ALTER COLUMN "crt_time" SET DEFAULT CURRENT_TIMESTAMP;
COMMENT ON COLUMN "base_config"."crt_time" IS '创建时间';
ALTER TABLE "base_config_scene" ALTER COLUMN "crt_time" TYPE timestamp;
ALTER TABLE "base_config_scene" ALTER COLUMN "crt_time" SET NOT NULL;
ALTER TABLE "base_config_scene" ALTER COLUMN "crt_time" SET DEFAULT CURRENT_TIMESTAMP;
COMMENT ON COLUMN "base_config_scene"."crt_time" IS '创建时间';
ALTER TABLE "base_config_sys" ALTER COLUMN "crt_time" TYPE timestamp;
ALTER TABLE "base_config_sys" ALTER COLUMN "crt_time" SET NOT NULL;
ALTER TABLE "base_config_sys" ALTER COLUMN "crt_time" SET DEFAULT CURRENT_TIMESTAMP;
COMMENT ON COLUMN "base_config_sys"."crt_time" IS '创建时间';
ALTER TABLE "base_department" ALTER COLUMN "crt_time" TYPE timestamp;
ALTER TABLE "base_department" ALTER COLUMN "crt_time" SET NOT NULL;
ALTER TABLE "base_department" ALTER COLUMN "crt_time" SET DEFAULT CURRENT_TIMESTAMP;
COMMENT ON COLUMN "base_department"."crt_time" IS '创建时间';
ALTER TABLE "base_dict" ALTER COLUMN "crt_time" TYPE timestamp;
ALTER TABLE "base_dict" ALTER COLUMN "crt_time" SET NOT NULL;
ALTER TABLE "base_dict" ALTER COLUMN "crt_time" SET DEFAULT CURRENT_TIMESTAMP;
COMMENT ON COLUMN "base_dict"."crt_time" IS '创建时间';
ALTER TABLE "base_entity_log" ALTER COLUMN "crt_time" TYPE timestamp;
ALTER TABLE "base_entity_log" ALTER COLUMN "crt_time" SET NOT NULL;
ALTER TABLE "base_entity_log" ALTER COLUMN "crt_time" SET DEFAULT CURRENT_TIMESTAMP;
COMMENT ON COLUMN "base_entity_log"."crt_time" IS '创建时间';
ALTER TABLE "base_file_biz" ALTER COLUMN "crt_time" TYPE timestamp;
ALTER TABLE "base_file_biz" ALTER COLUMN "crt_time" SET NOT NULL;
ALTER TABLE "base_file_biz" ALTER COLUMN "crt_time" SET DEFAULT CURRENT_TIMESTAMP;
COMMENT ON COLUMN "base_file_biz"."crt_time" IS '创建时间';
ALTER TABLE "base_file_save" ALTER COLUMN "crt_time" TYPE timestamp;
ALTER TABLE "base_file_save" ALTER COLUMN "crt_time" SET NOT NULL;
ALTER TABLE "base_file_save" ALTER COLUMN "crt_time" SET DEFAULT CURRENT_TIMESTAMP;
COMMENT ON COLUMN "base_file_save"."crt_time" IS '创建时间';
ALTER TABLE "base_job" ALTER COLUMN "crt_time" TYPE timestamp;
ALTER TABLE "base_job" ALTER COLUMN "crt_time" SET NOT NULL;
ALTER TABLE "base_job" ALTER COLUMN "crt_time" SET DEFAULT CURRENT_TIMESTAMP;
COMMENT ON COLUMN "base_job"."crt_time" IS '创建时间';
ALTER TABLE "base_log_api" ALTER COLUMN "crt_time" TYPE timestamp;
ALTER TABLE "base_log_api" ALTER COLUMN "crt_time" SET NOT NULL;
ALTER TABLE "base_log_api" ALTER COLUMN "crt_time" SET DEFAULT CURRENT_TIMESTAMP;
COMMENT ON COLUMN "base_log_api"."crt_time" IS '创建时间';
ALTER TABLE "base_log_login" ALTER COLUMN "crt_time" TYPE timestamp;
ALTER TABLE "base_log_login" ALTER COLUMN "crt_time" SET NOT NULL;
ALTER TABLE "base_log_login" ALTER COLUMN "crt_time" SET DEFAULT CURRENT_TIMESTAMP;
COMMENT ON COLUMN "base_log_login"."crt_time" IS '创建时间';
ALTER TABLE "base_msg" ALTER COLUMN "crt_time" TYPE timestamp;
ALTER TABLE "base_msg" ALTER COLUMN "crt_time" SET NOT NULL;
ALTER TABLE "base_msg" ALTER COLUMN "crt_time" SET DEFAULT CURRENT_TIMESTAMP;
COMMENT ON COLUMN "base_msg"."crt_time" IS '创建时间';
ALTER TABLE "base_notice" ALTER COLUMN "crt_time" TYPE timestamp;
ALTER TABLE "base_notice" ALTER COLUMN "crt_time" SET NOT NULL;
ALTER TABLE "base_notice" ALTER COLUMN "crt_time" SET DEFAULT CURRENT_TIMESTAMP;
COMMENT ON COLUMN "base_notice"."crt_time" IS '创建时间';
ALTER TABLE "base_rbac_menu" ALTER COLUMN "crt_time" TYPE timestamp;
ALTER TABLE "base_rbac_menu" ALTER COLUMN "crt_time" SET NOT NULL;
ALTER TABLE "base_rbac_menu" ALTER COLUMN "crt_time" SET DEFAULT CURRENT_TIMESTAMP;
COMMENT ON COLUMN "base_rbac_menu"."crt_time" IS '创建时间';
ALTER TABLE "base_rbac_role" ALTER COLUMN "crt_time" TYPE timestamp;
ALTER TABLE "base_rbac_role" ALTER COLUMN "crt_time" SET NOT NULL;
ALTER TABLE "base_rbac_role" ALTER COLUMN "crt_time" SET DEFAULT CURRENT_TIMESTAMP;
COMMENT ON COLUMN "base_rbac_role"."crt_time" IS '创建时间';
ALTER TABLE "base_rbac_role_menu" ALTER COLUMN "crt_time" TYPE timestamp;
ALTER TABLE "base_rbac_role_menu" ALTER COLUMN "crt_time" SET NOT NULL;
ALTER TABLE "base_rbac_role_menu" ALTER COLUMN "crt_time" SET DEFAULT CURRENT_TIMESTAMP;
COMMENT ON COLUMN "base_rbac_role_menu"."crt_time" IS '创建时间';
ALTER TABLE "base_rbac_user_role" ALTER COLUMN "crt_time" TYPE timestamp;
ALTER TABLE "base_rbac_user_role" ALTER COLUMN "crt_time" SET NOT NULL;
ALTER TABLE "base_rbac_user_role" ALTER COLUMN "crt_time" SET DEFAULT CURRENT_TIMESTAMP;
COMMENT ON COLUMN "base_rbac_user_role"."crt_time" IS '创建时间';
ALTER TABLE "base_sms_code" ALTER COLUMN "crt_time" TYPE timestamp;
ALTER TABLE "base_sms_code" ALTER COLUMN "crt_time" SET NOT NULL;
ALTER TABLE "base_sms_code" ALTER COLUMN "crt_time" SET DEFAULT CURRENT_TIMESTAMP;
COMMENT ON COLUMN "base_sms_code"."crt_time" IS '创建时间';
ALTER TABLE "base_system_update_log" ALTER COLUMN "crt_time" TYPE timestamp;
ALTER TABLE "base_system_update_log" ALTER COLUMN "crt_time" SET NOT NULL;
ALTER TABLE "base_system_update_log" ALTER COLUMN "crt_time" SET DEFAULT CURRENT_TIMESTAMP;
COMMENT ON COLUMN "base_system_update_log"."crt_time" IS '创建时间';
ALTER TABLE "base_user" ALTER COLUMN "crt_time" TYPE timestamp;
ALTER TABLE "base_user" ALTER COLUMN "crt_time" SET NOT NULL;
ALTER TABLE "base_user" ALTER COLUMN "crt_time" SET DEFAULT CURRENT_TIMESTAMP;
COMMENT ON COLUMN "base_user"."crt_time" IS '创建时间';
ALTER TABLE "base_user_token" ALTER COLUMN "crt_time" TYPE timestamp;
ALTER TABLE "base_user_token" ALTER COLUMN "crt_time" SET NOT NULL;
ALTER TABLE "base_user_token" ALTER COLUMN "crt_time" SET DEFAULT CURRENT_TIMESTAMP;
COMMENT ON COLUMN "base_user_token"."crt_time" IS '创建时间';
